name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: nikhilchauhan567
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/snake.svg"
